#!/usr/bin/env bash
# Configure Nginx to run as nginx user on port 8080
sed -i 's/^user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-enabled/default
pkill nginx
sleep 1
/usr/sbin/nginx
ps aux | grep nginx