#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header X-Served-By
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i "s/# server_tokens off;/server_tokens off;\n\tadd_header X-Served-By \$HOSTNAME;/" /etc/nginx/nginx.conf
sed -i "/server_name _;/a \\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart