#!/usr/bin/env bash
# Configures Nginx with a custom 404 page containing "Ceci n'est pas une page"
sudo apt-get update -y
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo sed -i '/server_name _;/a \\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart